#!/bin/bash

echo "🚀 Setting up Supabase Storage for Content Uploads"
echo "=================================================="
echo ""

# Check if .env.local exists
if [ ! -f ".env.local" ]; then
    echo "📝 Creating .env.local file..."
    cp env.example .env.local
    echo "✅ .env.local created from env.example"
    echo ""
    echo "⚠️  IMPORTANT: You need to edit .env.local with your Supabase credentials:"
    echo "   1. Go to your Supabase project dashboard"
    echo "   2. Copy your project URL and anon key"
    echo "   3. Edit .env.local and replace the placeholder values"
    echo ""
else
    echo "✅ .env.local already exists"
fi

echo "🔧 Supabase Storage Configuration Steps:"
echo ""
echo "1. 🌐 Go to your Supabase project dashboard"
echo "   - Navigate to: https://supabase.com/dashboard"
echo "   - Select your project"
echo ""
echo "2. 📦 Create Storage Bucket:"
echo "   - Click 'Storage' in the left sidebar"
echo "   - Click 'New bucket'"
echo "   - Name: 'content'"
echo "   - Public bucket: ✅ CHECKED"
echo "   - File size limit: 50 MB"
echo "   - Click 'Create bucket'"
echo ""
echo "3. 🔒 Configure RLS Policies:"
echo "   - In Storage, click 'Policies' tab"
echo "   - Add these policies for the 'content' bucket:"
echo ""
echo "   POLICY 1: 'Users can upload content'"
echo "   - Operation: INSERT"
echo "   - Condition: bucket_id = 'content' AND (storage.foldername(name))[1] = auth.uid()::text"
echo ""
echo "   POLICY 2: 'Users can view own content'"
echo "   - Operation: SELECT"
echo "   - Condition: bucket_id = 'content' AND (storage.foldername(name))[1] = auth.uid()::text"
echo ""
echo "   POLICY 3: 'Users can update own content'"
echo "   - Operation: UPDATE"
echo "   - Condition: bucket_id = 'content' AND (storage.foldername(name))[1] = auth.uid()::text"
echo ""
echo "   POLICY 4: 'Users can delete own content'"
echo "   - Operation: DELETE"
echo "   - Condition: bucket_id = 'content' AND (storage.foldername(name))[1] = auth.uid()::text"
echo ""
echo "   POLICY 5: 'Managers and admins can view all content'"
echo "   - Operation: SELECT"
echo "   - Condition: bucket_id = 'content' AND EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role IN ('manager', 'admin'))"
echo ""
echo "4. 🔑 Set environment variables:"
echo "   - Edit .env.local with your Supabase URL and anon key"
echo "   - Restart your development server"
echo ""
echo "5. 🧪 Test the system:"
echo "   - Go to /content/upload"
echo "   - Try uploading a file"
echo ""

echo "📚 For more help, check the Supabase documentation on Storage"
echo ""
echo "🎉 Setup instructions completed!"
